### ISSUE TITLE
Supervised Finetune on LLaMA-7B

### ISSUE THREAD

**Issue by cmnfriend** [nebuly-ai/nebullvm#255]
**I tried** `python main.py artifacts/config/config_uie.yaml --type ACTOR` **with the SHP dataset, but got nan loss.**

![1](https://user-images.githubusercontent.com/45878717/224522208-7c9e42bc-ec8f-4825-adf5-d5a3a5dd29fc.jpg)

**Here is my** `config_uie.yaml`**. The other parts (trainer_config, reward_config, critic_config) are the same with the original**  `config.yaml`**. Could you please tell me how I can fix this problem? Thank you! :)**

```
actor_config:
  model: "llama-7B"
  model_path: "/root/InstructUIE/run_llama/llama/7B"
  checkpoint_folder: "/root/InstructUIE/run_llama/llama/7B/checkpoints"
  tokenizer_folder: "/root/InstructUIE/run_llama/llama/tokenizer.model"
  train_dataset_path: "./datasets/actor_training_data.json"
  validation_dataset_path: null
  froze_embeddings: True
  use_fairscale: True
  max_sequence_length: 1024
  max_tokens: 512
  temperature: 0.8
  batch_size: 1
  iteration_per_print: 1
  lr: 0.00001
  epochs: 3
  deepspeed_enable: False
  deepspeed_config_path: "/root/InstructUIE/ds_configs/stage2_llama.config"
```

**Comment by HuangLK** [comment]
try to use `bf16`, work for me

**Comment by cmnfriend** [comment]
> try to use `bf16`, work for me

It works! Thanks a lot!

**Comment by wgimperial** [comment]
@cmnfriend Same problem, Could you please share your working config file that use bf16? Thank you!

**Comment by cmnfriend** [comment]
> @cmnfriend Same problem, Could you please share your working config file that use bf16? Thank you!

**config.yaml**
```
actor_config:
  model: "llama-7B"
  model_path: "/root/InstructUIE/run_llama/llama/7B"
  checkpoint_folder: "/root/InstructUIE/run_llama/llama/7B/checkpoints"
  tokenizer_folder: "/root/InstructUIE/run_llama/llama/tokenizer.model"
  train_dataset_path: "/root/InstructUIE/run_llama/llama/UIE_text2text/UIE_train.json"
  validation_dataset_path: "/root/InstructUIE/run_llama/llama/UIE_text2text/UIE_dev.json"
  froze_embeddings: True
  use_fairscale: True
  max_sequence_length: 1024
  max_tokens: 512
  temperature: 0.8
  batch_size: 1
  iteration_per_print: 1
  lr: 0.00001
  epochs: 3
  deepspeed_enable: True
  deepspeed_config_path: "./artifacts/config/ds_config_llama.json
```

**ds_config**
```
{
    "train_micro_batch_size_per_gpu": 1,
    "gradient_accumulation_steps": 16,
    "bfloat16": {
        "enabled": true
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 0.0001,
            "betas": [0.9, 0.999],
            "eps": 1e-8,
            "weight_decay": 0.1
        }
    },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true
    }
}
```
